project_id = "xushmvtkfkijrhfoxhat"

[functions.checkout]
verify_jwt = true

[functions.generate-batches]
verify_jwt = false

[functions.send-notification]
verify_jwt = false

[functions.send-cutoff-reminders]
verify_jwt = false